src/TheWorld/Models/Trip.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.Models
{
    public class Trip
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }
        public string UserName { get; set; }
        //public int MyProperty { get; set; }
        public ICollection<Stop> Stops  { get; set; }



    }
}

src/TheWorld/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TheWorld.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        [StringLength(255, MinimumLength =5)]
        public string Name { get; set; }


        [Required]
        [EmailAddress]
        public string Email { get; set; }


        [Required]
        [StringLength(1024, MinimumLength = 5)]
        public string Message { get; set; }
    }
}

src/TheWorld/ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TheWorld.Controllers.Api
{
    public class TripViewModel
    {
        
        public int Id { get; set; }
        [Required]
        [StringLength(255, MinimumLength = 5)]
        public string Name { get; set; }

        public DateTime Created { get; set; } = DateTime.UtcNow;

        public IEnumerable<StopViewModel> Stops { get; set; }

    }
}

src/TheWorld/Controllers/Api/TripController.cs
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using TheWorld.Models;

namespace TheWorld.Controllers.Api
{

    [Authorize]
    [Route("api/trips")]
    public class TripController :Controller
    {
        private ILogger<TripController> _logger;
        private IWorldRepository _repository;

        public TripController (IWorldRepository repository, ILogger<TripController> Logger)
        {
            _repository = repository;
            _logger = Logger;
        }


        [HttpGet("")]
        public JsonResult Get()
        {
<<<<<<< HEAD
            return Json(AutoMapper.Mapper.Map<IEnumerable<StopViewModel>>(_repository.GetAllTripsWithStops()));
=======
            var trips = _repository.GetUserTripsWithStops(User.Identity.Name);
            var results = AutoMapper.Mapper.Map<IEnumerable<TripViewModel>>(_repository.GetAllTripsWithStops());
            return Json(results);
>>>>>>> 036c636763d4c51ac646a581213af65261fc34b3
        }

        [HttpPost("")]
        public JsonResult Post([FromBody] TripViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var newTrip = AutoMapper.Mapper.Map<Trip>(vm);
                    newTrip.UserName = User.Identity.Name;
                    _logger.LogInformation("Attemping to save a new trip");
                    _repository.AddTrip(newTrip);

                    if (_repository.SaveAll())
                    {
                        Response.StatusCode = (int)HttpStatusCode.Created;
                        return Json(AutoMapper.Mapper.Map<TripViewModel>(newTrip));
                    }

                }
            }
            catch (Exception ex)
            {
                _logger.LogError("Failed to save new trip", ex);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Message = ex.Message });

            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(new { Message = "failed", ModelState = ModelState });
        }
    }
}

src/TheWorld/Controllers/Web/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using TheWorld.ViewModels;
using TheWorld.Services;
using TheWorld.Models;
using Microsoft.AspNet.Authorization;

namespace TheWorld.Controllers.Web
{
    public class AppController:Controller
    {
        private IMailService _mailService;
        private IWorldRepository _repository;

        public AppController(IMailService Service, IWorldRepository context)
        {
            _mailService = Service;
            _repository = context;

        }
        public IActionResult Index()
        {
          
            return View();
        }


        [Authorize] 
        public IActionResult Trips()
        {
            var trips = _repository.GetAllTrips();
            return View(trips);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
        

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            { 

                var email = Startup.configuration["AppSettings:SiteEmailAddress"];

                if (string.IsNullOrWhiteSpace(email))
                {
                    ModelState.AddModelError("","Could not send email, configuration problem.");
                }
               if ( _mailService.SendMail(email, email,$"Contact Page from {model.Name} ({model.Email})",model.Message))
               {
                    ModelState.Clear();

                    ViewBag.Message = "Mail Sent.Thanks!";
               }
                
            }
            return View();
        }
    }
}

src/TheWorld/Views/App/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "About Page";

}

<h2>
    About The World
</h2>

src/TheWorld/Views/App/Contact.cshtml
@model TheWorld.ViewModels.ContactViewModel

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    ViewBag.Title = "Contact Page";
    
}

@section Scripts {
    <script src="~/lib/jQuery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}


<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2> Contact Info</h2>

        <form method="post">
            @if (ViewBag.Message != null)
            {
                <div>
                    @ViewBag.Message
                </div>

            }
            <div asp-validation-summary="ValidationSummary.ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name"> Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-muted"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"> Email </label>
                <input type="email" asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-muted"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message">Message</label>
                <textarea asp-for="Message" cols="40" rows="4" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-muted"></span>
            </div>
            <div class="form-grousp">
                <a asp-controller="App" asp-action="Index" class="btn btn-default">Canel</a>
                <input type="submit" value="Send Message" class="btn btn-success" />
            </div>
        </form>
        </div>
    </div>

src/TheWorld/Views/App/Index.cshtml
@model IEnumerable<TheWorld.Models.Trip>

@{ 
    ViewBag.Title = "HomePage";
}


<!DOCTYPE html>
<html>
<head>
    <title>The World - @ViewBag.Title</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="row">
        <div class="col-md-12">
            <h1> Welcome to The World</h1>
            <p> This app will allow you to plan for world trip</p>
            <a asp-controller="App" asp-action="trips" class="btn btn-lg btn-success"> View My Trips</a>

        </div>

    </div>


</body>
</html>

src/TheWorld/Views/App/Trips.cshtml
@model IEnumerable<TheWorld.Models.Trip>

@{ 
    ViewBag.Title = "HomePage";
}
@section Scripts{
    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/js/simpleControls.js"></script>


}

<!DOCTYPE html>
<html>
<head>
    <title>The World - @ViewBag.Title</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>



}

<!DOCTYPE html>
<html>
<head>
    <title>The World - @ViewBag.Title</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="row" ng-app ="app-trips">
        <div ng-controller="tripsController as vm" class="col-md-6 col-md-offset-3">
            <div class="text-danger" ng-show="vm.errorMessage">{{vm.errorMessage}}</div>
            @*<wait-cursor display-When="vb.isBusy"></wait-cursor>*@
            <table class="table table-responsive table-striped">
                <tr ng-repeat="trip in vm.trips">
                    <td>{{trip.name}}</td>
                    <td>{{trip.created | date:'shortDate' }}</td>
                    <td><a href="#" class="btn btn-sm btn-primary">Manage</a></td>

                </tr>

            </table>

            <form novalidate name="newTripForm" ng-submit="vm.addTrip()">
                <div class="form-group">
                    <label for="name">Trip Name</label>
                    <input class="form-control" type="text" id="name" name="name" ng-model="vm.newTrip.name" required ng-minlength="5"/>                
                    <span ng-show="newTripForm.name.$error.required" class="text-warning"> Name is required. </span>
                    <span ng-show="newTripForm.name.$error.minlength" class="text-warning"> minimum length needs to be 5. </span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Add" class="btn btn-success btn-sm" ng-disabled="newTripForm.$invalid" />

                </div>

            </form>

        </div>






        <div class="col-md-6">
            <h2> The World</h2>
            <p>This will be a fun website</p>

            <form>
                <div class="form-group">
                    <label>Date</label>
                    <input class="form-control" />
                </div>
                <div class="form-group">
                    <label>Location</label>
                    <input class="form-control" />
                </div>
                <div><input type="submit" value="Add" class="form-control" /></div>
            </form>
        </div>
        <div class="col-md-6">
            <h2>The Map</h2>
            <ul>
            @foreach (var trip in Model)
            {
                    <li>@trip.Name (@trip.Created.ToShortDateString())</li>

                }
            </ul>
        </div>

    </div>


</body>
</html>