src/TheWorld/Controllers/Api/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Identity;
using TheWorld.Models;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Api
{
    public class AuthController : Controller
    {
        private SignInManager<WorldUser> _signInManager;

        public AuthController(SignInManager<WorldUser> signInManager)
        {
            _signInManager = signInManager;
        }


        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Trips", "App");
            }


            return View();
        }


        [HttpPost]
        public  async Task<ActionResult> Login(LoginViewModel vm, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var signInResult = await  _signInManager.PasswordSignInAsync(vm.Username, vm.Password, true, false);
                if (signInResult.Succeeded)
                {
                    if (string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Trips", "App");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                    
                }
                else
                {
                    ModelState.AddModelError("", "UserName or Password incorrect");
                }
            }           
            return View();
        }


        public async Task<ActionResult>Logout()
        {
            if (User.Identity.IsAuthenticated )
            {
                await _signInManager.SignOutAsync();
            }
            return RedirectToAction("Index", "App");

        }
    }
}

src/TheWorld/Controllers/Web/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using TheWorld.ViewModels;
using TheWorld.Services;
using TheWorld.Models;
using Microsoft.AspNet.Authorization;

namespace TheWorld.Controllers.Web
{
    public class AppController:Controller
    {
        private IMailService _mailService;
        private IWorldRepository _repository;

        public AppController(IMailService Service, IWorldRepository context)
        {
            _mailService = Service;
            _repository = context;

        }
        public IActionResult Index()
        {
          
            return View();
        }


        [Authorize] 
        public IActionResult Trips()
        {
            var trips = _repository.GetAllTrips();
            return View(trips);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
        

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            { 

                var email = Startup.configuration["AppSettings:SiteEmailAddress"];

                if (string.IsNullOrWhiteSpace(email))
                {
                    ModelState.AddModelError("","Could not send email, configuration problem.");
                }
               if ( _mailService.SendMail(email, email,$"Contact Page from {model.Name} ({model.Email})",model.Message))
               {
                    ModelState.Clear();

                    ViewBag.Message = "Mail Sent.Thanks!";
               }
                
            }
            return View();
        }
    }
}

src/TheWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>The World </title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootswatch/yeti/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/Font-Awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <div id="sidebar">
        @if (User.Identity.IsAuthenticated)
        {
            <img src="~/img/image1.jpg" alt="headshot" class="headshot" />
            <span id="username">@User.Identity.Name</span>

        }

        <ul class="nav">
            <li class="active"><a asp-controller="App" asp-action="Index">Home </a></li>
            <li><a asp-controller="App" asp-action="About">About </a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        @if (User.Identity.IsAuthenticated)
        {
            <li><a asp-controller="App" asp-action="Trips">My Trips</a></li>
            <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
        }
        </ul>
    </div>

    <div id="wrapper">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button id="sidebarToggle" class="btn btn-primary">
                            <i class="fa fa-angle-left"></i>

                        </button>
                    </li>
                </ul>
                <a asp-controller="App" asp-action="Index" class="navbar-brand">The World</a>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-save"></i> Save
                        </a>
                    </li>

                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="fa fa-print"></i> Print
                        </a>
                    </li>
                </ul>


            </div>
        </nav>
        <div id="main" class="container-fluid">
            <div>
                @RenderBody()

            </div>
        </div>



        <div id="footer" class="container-fluid">
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <h4 class="text-center text-info"> &copy 2015 Front Tier Trading</h4>
            </div>
        </div>

    </div>

    <script type="text/javascript" src="~/lib/jQuery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>


    @RenderSection("Scripts", false)

</body>

</html>